[package]
name = "mpl-token-metadata-anchor"
version = "0.1.0"
description = "Metadata anchor plugin"
edition = "2021"

[lib]
name = "mpl_token_metadata_anchor"

[dependencies]
anchor-lang = "0.24.2"
mpl-token-metadata = { version = "1.2.10", features = ["no-entrypoint"] }
